[hotkeys]
menuHotkey="!t"
replLoadHotkey="!e"
replSelectLoadHotkey="^e"
replSelectLoadExecHotkey="+!e"
replResetHotkey="^r"
exitHotkey="+!t"

[external]
emailpath="C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe"
;filemanagerpath="%SystemRoot%\explorer.exe"
filemanagerpath="C:\Program Files\GPSoftware\Directory Opus\dopus.exe"

[config]
font="Calibri"
fontsize=10
dpiScale="on"
windowPosX=203
windowPosY=0
windowWidth=2952
windowHeight=1157
JAVA_TOOL_OPTIONS=
JAVA_OPTS=

[replcommands]
replcommand1=//:reset
replcommand2=--load the code--
replcommand3=//import $file.scalafxTest2_amm
replcommand4=--load the codeExec--


